"use client";

import { createReportFolder, deleteReport, duplicateReport, initialReports, listReportFolders, listReports, reportFolders, type ReportDefinition, type ReportVisibility } from "@/lib/informes-api";
import { getReportSourceAdapter } from "@/lib/informes-metadata-provider";
import { listDashboards, type DashboardDefinition } from "@/lib/paneles-api";
import { Copy, ExternalLink, FileBarChart, Folder, FolderPlus, Pencil, Plus, Search, Share2, Trash2, X } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ReportVisibilityBadge } from "./report-ui";

const filters: Array<{ id: "all" | "mine" | "recent" | ReportVisibility; label: string }> = [{ id: "all", label: "Todos" }, { id: "mine", label: "Mis informes" }, { id: "shared", label: "Compartidos conmigo" }, { id: "private", label: "Privados" }, { id: "recent", label: "Recientes" }];
const formatDate = (value: string) => new Intl.DateTimeFormat("es-CL", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value));

export function InformesListView() {
  const [reports, setReports] = useState(initialReports);
  const [folders, setFolders] = useState(reportFolders);
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState<(typeof filters)[number]["id"]>("all");
  const [folderId, setFolderId] = useState("all");
  const [folderModal, setFolderModal] = useState(false);
  const [folderName, setFolderName] = useState("");
  const [shareReport, setShareReport] = useState<ReportDefinition | null>(null);
  const [dashboards, setDashboards] = useState<DashboardDefinition[]>([]);

  useEffect(() => { const id = window.setTimeout(() => { setReports(listReports()); setFolders(listReportFolders()); setDashboards(listDashboards()); }, 0); return () => window.clearTimeout(id); }, []);
  const visible = useMemo(() => reports.filter((report) => {
    const queryMatch = `${report.name} ${report.description}`.toLowerCase().includes(query.toLowerCase());
    const folderMatch = ["all", "mine"].includes(folderId) || report.folderId === folderId;
    const filterMatch = filter === "all" || filter === "recent" || (filter === "mine" ? report.owner.id === "owner-1" : report.visibility === filter);
    return queryMatch && folderMatch && filterMatch;
  }), [reports, query, folderId, filter]);

  function addFolder() { if (!folderName.trim()) return; createReportFolder(folderName); setFolders(listReportFolders()); setFolderName(""); setFolderModal(false); }
  function remove(id: string) { if (!window.confirm("¿Eliminar este informe?")) return; deleteReport(id); setReports(listReports()); }
  function duplicate(id: string) { duplicateReport(id); setReports(listReports()); }

  return <div className="space-y-3 pb-6">
    <section className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><span className="rounded-xl bg-cyan-50 p-2.5 text-cyan-700"><FileBarChart className="h-5 w-5" /></span><div><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-cyan-700">Analytics Studio</p><h1 className="text-2xl font-extrabold text-slate-950">Informes</h1><p className="mt-0.5 text-xs text-slate-500">Crea informes reutilizables para alimentar paneles y análisis operativos.</p></div></div><div className="flex gap-2"><button type="button" onClick={() => setFolderModal(true)} className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-slate-200 px-3 text-xs font-bold text-slate-600"><FolderPlus className="h-4 w-4" /> Nueva carpeta</button><Link href="/informes/nuevo" className="inline-flex h-9 items-center gap-1.5 rounded-lg bg-blue-600 px-3 text-xs font-bold text-white"><Plus className="h-4 w-4" /> Nuevo informe</Link></div></section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-200 p-4 lg:flex-row lg:items-center lg:justify-between"><label className="flex h-9 w-full max-w-sm items-center gap-2 rounded-lg border border-slate-200 bg-slate-50 px-3"><Search className="h-4 w-4 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar informes..." className="w-full bg-transparent text-xs outline-none" /></label><div className="flex flex-wrap gap-1.5">{filters.map((item) => <button key={item.id} type="button" onClick={() => setFilter(item.id)} className={`rounded-full px-3 py-1.5 text-[10px] font-bold ${filter === item.id ? "bg-blue-600 text-white" : "bg-slate-100 text-slate-600"}`}>{item.label}</button>)}</div></div>
      <div className="grid min-h-[430px] lg:grid-cols-[190px_minmax(0,1fr)]"><aside className="border-b border-slate-200 p-3 lg:border-b-0 lg:border-r"><p className="px-2 pb-2 text-[9px] font-bold uppercase tracking-wider text-slate-400">Carpetas</p><nav className="grid grid-cols-2 gap-1 lg:grid-cols-1">{folders.map((folder) => <button key={folder.id} type="button" onClick={() => setFolderId(folder.id)} className={`flex items-center gap-2 rounded-lg px-2.5 py-2 text-left text-[11px] font-bold ${folderId === folder.id ? "bg-blue-50 text-blue-700" : "text-slate-600 hover:bg-slate-50"}`}><Folder className="h-3.5 w-3.5" />{folder.name}</button>)}</nav></aside>
        <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left"><thead className="bg-slate-50 text-[9px] font-bold uppercase tracking-wide text-slate-400"><tr><th className="px-4 py-2.5">Nombre</th><th className="px-3 py-2.5">Fuente</th><th className="px-3 py-2.5">Carpeta</th><th className="px-3 py-2.5">Visibilidad</th><th className="px-3 py-2.5">Dueño</th><th className="px-3 py-2.5">Actualización</th><th className="px-3 py-2.5 text-center">En paneles</th><th className="px-3 py-2.5 text-right">Acciones</th></tr></thead><tbody>{visible.map((report) => { const source = getReportSourceAdapter(report.source).source; const folder = folders.find((item) => item.id === report.folderId); const usage = dashboards.filter((dashboard) => dashboard.widgets.some((widget) => widget.reportId === report.id)).length; return <tr key={report.id} className="border-t border-slate-100 hover:bg-blue-50/30"><td className="px-4 py-3"><Link href={`/informes/${report.id}`} className="text-sm font-extrabold text-slate-900 hover:text-blue-600">{report.name}</Link><p className="mt-0.5 max-w-xs truncate text-[10px] text-slate-500">{report.description}</p></td><td className="px-3 text-[10px] font-bold text-cyan-700">{source.label}</td><td className="px-3 text-[10px] text-slate-600">{folder?.name || "—"}</td><td className="px-3"><ReportVisibilityBadge visibility={report.visibility} /></td><td className="px-3"><div className="flex items-center gap-2"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-slate-200 text-[8px] font-bold">{report.owner.initials}</span><span className="text-[10px] text-slate-600">{report.owner.name}</span></div></td><td className="px-3 text-[10px] text-slate-500">{formatDate(report.updatedAt)}</td><td className="px-3 text-center text-xs font-bold">{usage}</td><td className="px-3"><div className="flex justify-end gap-1"><Link title="Abrir" href={`/informes/${report.id}`} className="rounded-md p-1.5 text-slate-400 hover:bg-blue-50 hover:text-blue-600"><ExternalLink className="h-3.5 w-3.5" /></Link><Link title="Editar" href={`/informes/nuevo?edit=${report.id}`} className="rounded-md p-1.5 text-slate-400 hover:bg-slate-100"><Pencil className="h-3.5 w-3.5" /></Link><button title="Duplicar" type="button" onClick={() => duplicate(report.id)} className="rounded-md p-1.5 text-slate-400 hover:bg-slate-100"><Copy className="h-3.5 w-3.5" /></button><button title="Compartir" type="button" onClick={() => setShareReport(report)} className="rounded-md p-1.5 text-slate-400 hover:bg-slate-100"><Share2 className="h-3.5 w-3.5" /></button><button title="Eliminar" type="button" onClick={() => remove(report.id)} className="rounded-md p-1.5 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 className="h-3.5 w-3.5" /></button></div></td></tr>; })}</tbody></table></div>
      </div></section>
    {folderModal ? <div className="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/35 p-4"><div className="w-full max-w-sm rounded-2xl bg-white p-5 shadow-2xl"><div className="flex justify-between"><h2 className="font-extrabold">Nueva carpeta</h2><button type="button" onClick={() => setFolderModal(false)}><X className="h-4 w-4" /></button></div><input autoFocus value={folderName} onChange={(event) => setFolderName(event.target.value)} placeholder="Nombre de carpeta" className="mt-4 h-10 w-full rounded-lg border border-slate-200 px-3 text-sm outline-none" /><button type="button" onClick={addFolder} className="mt-4 h-9 w-full rounded-lg bg-blue-600 text-xs font-bold text-white">Crear carpeta</button></div></div> : null}
    {shareReport ? <div className="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/35 p-4"><div className="w-full max-w-sm rounded-2xl bg-white p-5 shadow-2xl"><h2 className="font-extrabold">Compartir “{shareReport.name}”</h2><p className="mt-2 text-xs text-slate-500">Los permisos reales se conectarán más adelante.</p><input placeholder="Buscar personas o equipos..." className="mt-4 h-10 w-full rounded-lg border border-slate-200 px-3 text-xs" /><button type="button" onClick={() => setShareReport(null)} className="mt-4 h-9 w-full rounded-lg bg-blue-600 text-xs font-bold text-white">Listo</button></div></div> : null}
  </div>;
}
