"use client";

import { createReportDraft, getReport, listReportFolders, reportFolders, saveReport, type ReportDefinition, type ReportMetric } from "@/lib/informes-api";
import { runReport } from "@/lib/informes-engine";
import { getAggregatableFields, getDefaultColumns, getFilterableFields, getGroupableFields, getReportFields, getReportSourceAdapter, getReportSources, getSortableFields } from "@/lib/informes-metadata-provider";
import { ArrowLeft, Check, ChevronRight, Database, Eye, Filter, Group, ListChecks, Save, Search, Sigma } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { ReportRunPreview } from "./report-ui";
import { useReportSource } from "./use-report-source";

const inputClass = "mt-1 h-9 w-full rounded-lg border border-slate-200 bg-white px-3 text-xs outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100";
const steps = [{ id: "source", label: "Fuente", icon: Database }, { id: "columns", label: "Columnas", icon: ListChecks }, { id: "filters", label: "Filtros", icon: Filter }, { id: "grouping", label: "Agrupaciones", icon: Group }, { id: "metrics", label: "Métricas", icon: Sigma }, { id: "preview", label: "Vista previa", icon: Eye }];

export function ReportBuilder({ editId }: { editId?: string }) {
  const router = useRouter();
  const [report, setReport] = useState(createReportDraft);
  const [folders, setFolders] = useState(reportFolders);
  const [activeStep, setActiveStep] = useState("source");
  const [fieldQuery, setFieldQuery] = useState("");
  const [fieldFilter, setFieldFilter] = useState<"all" | "standard" | "custom" | "dates" | "numeric" | "picklists">("all");
  const sourceRevision = useReportSource(report.source);
  useEffect(() => { const id = window.setTimeout(() => { if (editId) { const existing = getReport(editId); if (existing) setReport(existing); } setFolders(listReportFolders()); }, 0); return () => window.clearTimeout(id); }, [editId]);
  const reportSources = getReportSources();
  const source = getReportSourceAdapter(report.source).source;
  const reportFields = getReportFields(report.source);
  const filterableFields = getFilterableFields(report.source);
  const groupableFields = getGroupableFields(report.source);
  const aggregatableFields = getAggregatableFields(report.source);
  const sortableFields = getSortableFields(report.source);
  const visibleFields = reportFields.filter((field) => {
    const matchesQuery = `${field.label} ${field.name}`.toLocaleLowerCase("es-CL").includes(fieldQuery.toLocaleLowerCase("es-CL"));
    const matchesType = fieldFilter === "all" || (fieldFilter === "standard" && !field.isCustom) || (fieldFilter === "custom" && field.isCustom) || (fieldFilter === "dates" && ["date", "datetime"].includes(field.type)) || (fieldFilter === "numeric" && ["number", "currency"].includes(field.type)) || (fieldFilter === "picklists" && field.type === "picklist");
    return matchesQuery && matchesType;
  });
  const result = useMemo(() => runReport(report, sourceRevision), [report, sourceRevision]);

  function changeSource(sourceId: ReportDefinition["source"]) { const next = getReportSourceAdapter(sourceId).source; if (!next.enabled) return; const defaults = getDefaultColumns(sourceId); const sortable = getSortableFields(sourceId); setFieldQuery(""); setFieldFilter("all"); setReport({ ...report, source: sourceId, columns: defaults, filters: [], groupBy: [], metrics: [{ id: "records", aggregation: "count", label: "Recuento de registros" }], sort: { field: sortable[0]?.name || defaults[0], direction: "desc" } }); }
  function toggleColumn(key: string) { setReport({ ...report, columns: report.columns.includes(key) ? report.columns.filter((column) => column !== key) : [...report.columns, key] }); }
  function addFilter() { const first = filterableFields[0]; if (!first) return; setReport({ ...report, filters: [...report.filters, { id: `filter-${report.filters.length + 1}`, field: first.name, operator: "equals", value: "" }] }); }
  function changeAggregation(value: ReportMetric["aggregation"]) { if (value === "count") { setReport({ ...report, metrics: [{ id: "records", aggregation: "count", label: "Recuento de registros" }] }); return; } const selectedField = aggregatableFields[0]; if (!selectedField) return; const labels = { sum: "Suma", average: "Promedio", max: "Máximo", min: "Mínimo" }; setReport({ ...report, metrics: [{ id: `metric-${value}`, aggregation: value, field: selectedField.name, label: `${labels[value]} de ${selectedField.label}` }] }); }
  function changeMetricField(fieldName: string) { const metric = report.metrics[0]; const selectedField = aggregatableFields.find((field) => field.name === fieldName); if (!metric || !selectedField || metric.aggregation === "count") return; const labels = { sum: "Suma", average: "Promedio", max: "Máximo", min: "Mínimo" }; setReport({ ...report, metrics: [{ ...metric, field: fieldName, label: `${labels[metric.aggregation]} de ${selectedField.label}` }] }); }
  function save() { if (!report.name.trim()) { setActiveStep("source"); return; } const id = report.id || `${report.name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}-${Date.now()}`; saveReport({ ...report, id, updatedAt: new Date().toISOString() }); router.push(`/informes/${id}`); }

  return <div className="space-y-3 pb-6"><div className="flex items-center gap-1.5 text-[10px] font-semibold text-slate-500"><Link href="/informes">Informes</Link><ChevronRight className="h-3 w-3" /><span>{editId ? "Editar informe" : "Nuevo informe"}</span></div>
    <section className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-3"><Link href="/informes" className="rounded-lg border border-slate-200 p-2 text-slate-500"><ArrowLeft className="h-4 w-4" /></Link><div><h1 className="text-xl font-extrabold text-slate-950">{editId ? "Editar informe" : "Nuevo informe"}</h1><p className="text-xs text-slate-500">Define un informe reutilizable para análisis y paneles.</p></div></div><button type="button" onClick={save} disabled={!report.name.trim()} className="inline-flex h-9 items-center justify-center gap-1.5 rounded-lg bg-blue-600 px-4 text-xs font-bold text-white disabled:opacity-40"><Save className="h-4 w-4" /> Guardar informe</button></section>
    <div className="grid gap-3 lg:grid-cols-[190px_minmax(0,1fr)]"><aside className="h-fit rounded-xl border border-slate-200 bg-white p-2 shadow-sm">{steps.map(({ id, label, icon: Icon }, index) => <button key={id} type="button" onClick={() => setActiveStep(id)} className={`flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-[11px] font-bold ${activeStep === id ? "bg-blue-50 text-blue-700" : "text-slate-600 hover:bg-slate-50"}`}><span className={`flex h-6 w-6 items-center justify-center rounded-full text-[9px] ${activeStep === id ? "bg-blue-600 text-white" : "bg-slate-100"}`}>{index + 1}</span><Icon className="h-3.5 w-3.5" />{label}</button>)}</aside>
      <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
        {activeStep === "source" ? <div><h2 className="text-base font-extrabold">1. Fuente de datos</h2><p className="text-xs text-slate-500">Selecciona el objeto base y define la información general.</p><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{reportSources.map((item) => <button key={item.id} type="button" disabled={!item.enabled} onClick={() => changeSource(item.id)} className={`rounded-xl border p-3 text-left ${!item.enabled ? "cursor-not-allowed border-slate-200 bg-slate-50 opacity-70" : report.source === item.id ? "border-blue-500 bg-blue-50 ring-1 ring-blue-200" : "border-slate-200 hover:bg-slate-50"}`}><div className="flex items-center justify-between gap-2"><p className="text-sm font-extrabold">{item.label}</p>{!item.enabled ? <span className="rounded-full bg-amber-100 px-2 py-0.5 text-[8px] font-bold uppercase text-amber-700">Próximamente</span> : report.source === item.id ? <Check className="h-4 w-4 text-blue-600" /> : null}</div><p className="mt-1 text-[10px] leading-4 text-slate-500">{item.description}</p></button>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-[10px] font-bold uppercase text-slate-500">Nombre<input value={report.name} onChange={(event) => setReport({ ...report, name: event.target.value })} className={inputClass} placeholder="Ej. Casos por canal" /></label><label className="text-[10px] font-bold uppercase text-slate-500">Carpeta<select value={report.folderId} onChange={(event) => setReport({ ...report, folderId: event.target.value })} className={inputClass}>{folders.filter((folder) => !["all", "mine"].includes(folder.id)).map((folder) => <option key={folder.id} value={folder.id}>{folder.name}</option>)}</select></label><label className="text-[10px] font-bold uppercase text-slate-500 sm:col-span-2">Descripción<textarea value={report.description} onChange={(event) => setReport({ ...report, description: event.target.value })} className="mt-1 min-h-20 w-full rounded-lg border border-slate-200 p-3 text-xs outline-none" /></label><label className="text-[10px] font-bold uppercase text-slate-500">Visibilidad<select value={report.visibility} onChange={(event) => setReport({ ...report, visibility: event.target.value as ReportDefinition["visibility"] })} className={inputClass}><option value="private">Privado</option><option value="shared">Compartido</option><option value="internal">Público interno</option></select></label><label className="text-[10px] font-bold uppercase text-slate-500">Límite<input type="number" min="1" max="500" value={report.limit} onChange={(event) => setReport({ ...report, limit: Number(event.target.value) })} className={inputClass} /></label></div></div> : null}
        {activeStep === "columns" ? <div><h2 className="text-base font-extrabold">2. Columnas visibles</h2><p className="text-xs text-slate-500">Campos entregados dinámicamente por el provider de {source.label}.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row"><label className="flex h-9 flex-1 items-center gap-2 rounded-lg border border-slate-200 bg-slate-50 px-3"><Search className="h-3.5 w-3.5 text-slate-400" /><input value={fieldQuery} onChange={(event) => setFieldQuery(event.target.value)} placeholder="Buscar campos..." className="w-full bg-transparent text-xs outline-none" /></label><select value={fieldFilter} onChange={(event) => setFieldFilter(event.target.value as typeof fieldFilter)} className="h-9 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-600"><option value="all">Todos los campos</option><option value="standard">Campos estándar</option><option value="custom">Campos personalizados</option><option value="dates">Fechas</option><option value="numeric">Numéricos</option><option value="picklists">Picklists</option></select></div><p className="mt-2 text-[9px] font-semibold text-slate-400">{report.columns.length} seleccionados · {visibleFields.length} disponibles en este filtro</p><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{visibleFields.map((field) => <label key={field.name} className={`flex items-center gap-2 rounded-lg border p-3 text-xs font-semibold ${report.columns.includes(field.name) ? "border-blue-300 bg-blue-50 text-blue-700" : "border-slate-200 text-slate-600"}`}><input type="checkbox" checked={report.columns.includes(field.name)} onChange={() => toggleColumn(field.name)} className="accent-blue-600" /><span className="min-w-0"><span className="block truncate">{field.label}</span><span className="block truncate text-[8px] font-medium text-slate-400">{field.objectName}.{field.sourceField}</span></span><span className="ml-auto text-[8px] uppercase text-slate-400">{field.type}</span></label>)}</div>{!visibleFields.length ? <p className="mt-4 rounded-lg border border-dashed border-slate-300 py-8 text-center text-xs text-slate-400">No hay campos que coincidan con la búsqueda.</p> : null}</div> : null}
        {activeStep === "filters" ? <div><div className="flex items-center justify-between"><div><h2 className="text-base font-extrabold">3. Filtros</h2><p className="text-xs text-slate-500">Solo se muestran campos filtrables de {source.label}.</p></div><button type="button" onClick={addFilter} disabled={!filterableFields.length} className="rounded-lg bg-blue-50 px-3 py-2 text-[10px] font-bold text-blue-700 disabled:opacity-40">+ Agregar filtro</button></div><div className="mt-4 space-y-2">{report.filters.map((filter, index) => <div key={filter.id} className="grid gap-2 rounded-lg bg-slate-50 p-3 sm:grid-cols-[1fr_0.8fr_1fr_auto]"><select value={filter.field} onChange={(event) => setReport({ ...report, filters: report.filters.map((item, itemIndex) => itemIndex === index ? { ...item, field: event.target.value } : item) })} className={inputClass.replace("mt-1 ", "")}>{filterableFields.map((field) => <option key={field.name} value={field.name}>{field.label}</option>)}</select><select value={filter.operator} onChange={(event) => setReport({ ...report, filters: report.filters.map((item, itemIndex) => itemIndex === index ? { ...item, operator: event.target.value as typeof item.operator } : item) })} className={inputClass.replace("mt-1 ", "")}><option value="equals">Es igual a</option><option value="not_equals">No es igual a</option><option value="contains">Contiene</option><option value="greater_than">Mayor que</option><option value="less_than">Menor que</option><option value="between">Entre</option><option value="is_empty">Está vacío</option><option value="is_not_empty">No está vacío</option></select><div className="flex gap-1"><input disabled={["is_empty", "is_not_empty"].includes(filter.operator)} value={filter.value} onChange={(event) => setReport({ ...report, filters: report.filters.map((item, itemIndex) => itemIndex === index ? { ...item, value: event.target.value } : item) })} className={inputClass.replace("mt-1 ", "")} placeholder="Valor" />{filter.operator === "between" ? <input value={filter.valueTo || ""} onChange={(event) => setReport({ ...report, filters: report.filters.map((item, itemIndex) => itemIndex === index ? { ...item, valueTo: event.target.value } : item) })} className={inputClass.replace("mt-1 ", "")} placeholder="Hasta" /> : null}</div><button type="button" onClick={() => setReport({ ...report, filters: report.filters.filter((_, itemIndex) => itemIndex !== index) })} className="px-2 text-xs font-bold text-red-500">Quitar</button></div>)}{!report.filters.length ? <p className="rounded-lg border border-dashed border-slate-300 py-10 text-center text-xs text-slate-400">Sin filtros. El informe incluirá todos los registros.</p> : null}</div></div> : null}
        {activeStep === "grouping" ? <div><h2 className="text-base font-extrabold">4. Agrupaciones y orden</h2><p className="text-xs text-slate-500">Agrupa y ordena usando capacidades declaradas por metadata.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-[10px] font-bold uppercase text-slate-500">Agrupar por<select value={report.groupBy[0]?.field || ""} onChange={(event) => setReport({ ...report, groupBy: event.target.value ? [{ field: event.target.value, direction: "desc" }] : [] })} className={inputClass}><option value="">Sin agrupación</option>{groupableFields.map((field) => <option key={field.name} value={field.name}>{field.label}</option>)}</select></label><label className="text-[10px] font-bold uppercase text-slate-500">Ordenar por<select value={report.sort.field} onChange={(event) => setReport({ ...report, sort: { ...report.sort, field: event.target.value } })} className={inputClass}>{sortableFields.map((field) => <option key={field.name} value={field.name}>{field.label}</option>)}</select></label><label className="text-[10px] font-bold uppercase text-slate-500">Dirección<select value={report.sort.direction} onChange={(event) => setReport({ ...report, sort: { ...report.sort, direction: event.target.value as "asc" | "desc" } })} className={inputClass}><option value="asc">Ascendente</option><option value="desc">Descendente</option></select></label></div></div> : null}
        {activeStep === "metrics" ? <div><h2 className="text-base font-extrabold">5. Métricas</h2><p className="text-xs text-slate-500">Suma, promedio, máximo y mínimo solo aceptan campos numéricos o currency.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-[10px] font-bold uppercase text-slate-500">Agregación<select value={report.metrics[0]?.aggregation || "count"} onChange={(event) => changeAggregation(event.target.value as ReportMetric["aggregation"])} className={inputClass}><option value="count">Recuento de registros</option><option value="sum" disabled={!aggregatableFields.length}>Suma</option><option value="average" disabled={!aggregatableFields.length}>Promedio</option><option value="max" disabled={!aggregatableFields.length}>Máximo</option><option value="min" disabled={!aggregatableFields.length}>Mínimo</option></select></label><label className="text-[10px] font-bold uppercase text-slate-500">Campo<select disabled={report.metrics[0]?.aggregation === "count" || !aggregatableFields.length} value={report.metrics[0]?.field || ""} onChange={(event) => changeMetricField(event.target.value)} className={inputClass}><option value="">Seleccionar campo</option>{aggregatableFields.map((field) => <option key={field.name} value={field.name}>{field.label}</option>)}</select></label></div></div> : null}
        {activeStep === "preview" ? <div><div className="flex items-end justify-between"><div><h2 className="text-base font-extrabold">6. Vista previa</h2><p className="text-xs text-slate-500">Resultado ejecutado con filtros, agrupación, métrica, orden y límite.</p></div><p className="text-[10px] font-bold text-slate-500">{result.totalRows.toLocaleString("es-CL")} registros</p></div><div className="mt-4"><ReportRunPreview result={result} groupLabel={reportFields.find((field) => field.name === report.groupBy[0]?.field)?.label} metricLabel={report.metrics[0]?.label || "Recuento de registros"} /></div></div> : null}
      </section></div>
  </div>;
}
